config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :only => [:sessions], path: 'admin', path_names: { sign_in: 'login', sign_out: 'logout'}
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end
  
  #mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #

  namespace :api do
    namespace :v1, defaults: { format: :json } do
      resources :movies
      post :assign_favorite, to: 'favorites#assign_favorite'
      post :login, to: 'login#login_viewer'
      post :remove_favorite, to: 'favorites#remove_favorite'
      get :fav_movies, to: 'favorites#fav_movies'
    end
  end

  namespace :admin do
    resources :movies
    resources :users
    root 'movies#index'
  end

  root "admin/movies#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,  :validatable, :rememberable
  # :registerable, :recoverable, :rememberable,
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_viewer, only: [:show, :destroy]

  def index
    @viewers = Viewer.all.paginate(page: params[:page], per_page: 25)
  end

  def show;end

  def destroy
    # remove favorites
    @viewer.adjust_favorite_number
    # remove viewer
    @viewer.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_viewer
    @viewer = Viewer.find(params[:id])
  end
end

app/views/admin/users/index.html.erb
<div class="row">
  <div class="col-12">
    <div class="card">
      <!-- /.card-header -->
      <div class="card-body table-responsive p-0">
        <table class="table table-hover text-nowrap">
          <thead>
          <tr>
            <th>Username</th>
            <th>Number Favorite Movies</th>
            <th colspan="3"></th>
          </tr>
          </thead>

          <tbody>
          <% @viewers.each_with_index do |viewer, index| %>
            <tr>
              <td><%= link_to viewer.username, admin_user_path(viewer) %></td>
              <td><%= pluralize(viewer.movies.count, "time") %> Favorited </td>
              <td><%= link_to 'Delete', admin_user_path(viewer),  method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
          </tbody>
        </table>

      </div>
      <div class="card-footer clearfix">
        <%= will_paginate @viewers %>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->
  </div>
</div>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Username:</strong>
  <%= @viewer.username %>
</p>
<p>
  <strong>Movie List:</strong>
  <br/>
  <% @viewer.movies.each do |mv|%>
    <%= mv.name %></br>
  <% end %>
</p>
<%= link_to 'Back', admin_users_path %>